version: "3"
services:
 client-server:

    image: client-server-img
    container_name: client-server-cont
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:5000
    restart: unless-stopped
